Спринт 11. Первая версия
eklerkjke/java-filmorate pull request #6
Opened 2024-10-18 17:58 UTC by eklerkjke

Спринт 11. Первая версия

2024-10-19 17:32 UTC, afomkina requested changes

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Несколько лишних отступов

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getById(@PathVariable Long userId) {
В пути переменная называется `id`, а в параметрах `userId`. Нужно поддерживать единообразие имен, поэтому нужно переименовать либо путь, либо название параметра

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(NotFoundException.class)
Нужно убрать полный путь до аннотации и вынести его в импорты

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleNotFoundException(final NotFoundException e) {
Можно сделать код еще лаконичнее, избавившись от обертки `ResponseEntity`. Для этого нужно просто добавить аннотацию `@ResponseStatus(HttpStatus.NOT_FOUND)` над методом, а в самом методе возвращать `ErrorResponse`

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = filmStorage.getById(filmId);
Код со строк 37-45 повторяется ниже на строках 51-59. Нужео его вынести в отельный метод и переиспользовать

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserStorage userStorage;
Должен быть `final`

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        HashSet<Long> intersect = new HashSet<>(getById(id).getFriends());
Нужно обозначать интерфейс, а создавать объект с определенной реализацией

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +public class ExceptionHandler {
Нужно возвращать 500 — если возникло исключение

2024-10-19 17:32 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.sort(new TopFilmsComparator());
Сортировку можно сделать в стриме первым действием на 68 строке с помощью метода
`.sorted(FILM_COMPARATOR)`

2024-10-21 00:21 UTC, afomkina requested changes

2024-10-21 00:21 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateExceptionHandler.java
> +    public ErrorResponse handleBadRequestException(final BadRequestException e) {
Здесь лучше отлавливать не `BadRequestException`, а все `Throwable`. А вот `BadRequest` обычно возвращает код ответа 400. Есть отдельный статус `HttpStatus.BAD_REQUEST`

2024-10-21 00:21 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = new ArrayList<>(getList());
Дополнительно оборачивать `getList()` в список не нужно, так как метод и так возвращает список по которому можно запустить стрим на 53 строке

2024-10-21 19:34 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getById(@PathVariable Long userId) {
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(NotFoundException.class)
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleNotFoundException(final NotFoundException e) {
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserStorage userStorage;
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        HashSet<Long> intersect = new HashSet<>(getById(id).getFriends());
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/exception/ExceptionHandler.java
> +public class ExceptionHandler {
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.sort(new TopFilmsComparator());
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateExceptionHandler.java
> +    public ErrorResponse handleBadRequestException(final BadRequestException e) {
поправил

2024-10-21 19:35 UTC, eklerkjke commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = new ArrayList<>(getList());
поправил

2024-10-21 20:22 UTC, afomkina requested changes

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Здесь нужно возвращать `HttpStatus.INTERNAL_SERVER_ERROR`

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateExceptionHandler.java
> +    @ExceptionHandler(NotFoundException.class)
Чтобы корректно обрабатывать все исключения надо также ловить ошибки от валидации и возвращать корректный код ответа:
```suggestion
     @ExceptionHandler({NotFoundException.class, MethodArgumentNotValidException.class})
```

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateExceptionHandler.java
> +    @ExceptionHandler(BadRequestException.class)
Здесь нужно также отлавливать `HttpMessageNotReadableException.class`

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new SystemException("Нельзя доабвить пользователя с таким ID: " + user.getId());
Здесь нужно выбрасывать `BadRequestException`,  как и было раньше

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new SystemException("Нельзя доабвить фильм с таким ID: " + film.getId());
Здесь нужно выбрасывать `BadRequestException`,  как и было раньше

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/SystemException.java
> +public class SystemException extends RuntimeException {
Это исключение нам больше не понадобится, нужно его удалить

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = new ArrayList<>(getList());
Не поправил

2024-10-21 20:22 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return films
```suggestion
        return getList()
```

2024-10-22 12:45 UTC, afomkina approved these changes

2024-10-27 09:28 UTC, merged